### ISSUE TITLE
报错：IndexError: list index out of range

### ISSUE THREAD

**Issue by chad-cai** [MalitsPlus/HoshimiToolkit#1]
我在尝试执行的时候每次都会报这个错，我的python版本是3. 10：
C:\Users\csccs\Desktop\HoshimiToolkit-master>python ipr/main.py
[1m>>> [0m[1m[[0m[1mInfo[0m[1m][0m Current revision : [1;36m1520[0m

[1;32m>>> [0m[1;32m[[0m[1;32mSucceed[0m[1;32m][0m Decrypted cache has been written into ipr\DecryptedCaches\manifest_v1520.

[1;32m>>> [0m[1;32m[[0m[1;32mSucceed[0m[1;32m][0m Tables have been created successfully.

[1;32m>>> [0m[1;32m[[0m[1;32mSucceed[0m[1;32m][0m All data has been written into SQLite database.

Traceback (most recent call last):
  File "C:\Users\csccs\Desktop\HoshimiToolkit-master\ipr\main.py", line 12, in <module>
    jDict = doDecrypt(diffMode)
  File "C:\Users\csccs\Desktop\HoshimiToolkit-master\ipr\ManifestDecryptor.py", line 339, in doDecrypt
    diffDict = __diffRevision(jDict)
  File "C:\Users\csccs\Desktop\HoshimiToolkit-master\ipr\ManifestDecryptor.py", line 244, in __diffRevision
    previousOne = manifestList[0]
IndexError: list index out of range

我检查了几遍asset和EncryptedCache都没放错，我应该也没缺什么module
求助大佬这个该怎么破，是我自己的问题话我需要做什么呢...

**Comment by MalitsPlus** [comment]
嘛...这个算是我故意设的一个坎吧 ~~（其实是懒得改~~ 
 
我不希望这个工具能被随便是个人就能使用，那样也许会导致滥用和剧透 
请依靠自己的知识解决这个bug吧，这个bug其实很简单的，有点基础的稍微看一下就能解决了

**Comment by chad-cai** [comment]
原来如此，那大佬介意给个小提示之类的嘛（因为我自己没学过python...）

**Comment by MalitsPlus** [comment]
你这路子歪的我都不知道该说啥了......😓

**Comment by chad-cai** [comment]
不愧是我。。。那大佬可以给个提示吗，我这盲人摸象属实搞不太明白😭

**Comment by chad-cai** [comment]
好了我给他搞定了，确实不是啥大坎，我之前路走太歪了（笑），感谢大佬让我度过了几个有意义的小时（狗头）
顺带一提，大佬你的简介有个语法问题，应该是deals with才对（

**Comment by MalitsPlus** [comment]
没事，正好可以证明我英语是体育老师教的（

**Comment by RabberDakk** [comment]
I was going to send a Pull Request, but after seeing this Issue I decided not to :wink:  Many thanks for your work! This analysis was probably impossible for me.

**Comment by MalitsPlus** [comment]
Actually nothing special. It's just a draft I wrote while thinking.

**Comment by Chrisraine** [comment]
大佬，我不是专业的对代码一窍不通，这两天为了解包这个游戏用尽了浑身解数，只是为了一张喜欢的麻奈的卡图和动画，可以给个资源吗，只用做壁纸和收藏，不会乱传播，万分感谢了！🙏

**Comment by Chrisraine** [comment]
嗨，就这
