### ISSUE TITLE
Idoly Pride 解密出现语法错误 syntax error

### ISSUE THREAD

**Issue by Discovererian** [MalitsPlus/HoshimiToolkit#10]
我按照readme文件中的方法将文件移动到目录并直接启动Main.py。但是终端提示在程序中有语法错误。运行环境都装了，错误提示如图，![serr.png](https://user-images.githubusercontent.com/101110223/174482079-e2748bb8-398d-46d4-9c67-8fdcfa70a595.png)望解答一下，谢谢。

**Comment by MalitsPlus** [comment]
请自行安装python 3+(

**Comment by Discovererian** [comment]
感谢，回去发现有些库没安装完，现在解决了
