### ISSUE TITLE
Cannot open IDOLY PRIDE unobfuscated files models!

### ISSUE THREAD

**Issue by thesolitudeofnoblesoul** [MalitsPlus/HoshimiToolkit#6]
Tool run successful but I don't know if anything went wrong here!
I can not open asset files with any program like: AssetStudio, AssetRipper, uTinyRipper. All thow out error!

Can you please check it out! There are sample in case you need:
[octocacheevai](https://drive.google.com/file/d/1-bzoO3xLbyywauPiAWo-j3Q-hxulkAbB/view)
[mdl_chr_ai-base-00_face.unity3d](https://drive.google.com/file/d/1-bgXwegUiSmwDLagqRAZUrqGC8KXGLn9/view)
[mdl_chr_ai-base-00_hair.unity3d](https://drive.google.com/file/d/1-ZAbqNk0TmcKM2xBrltZzmeZiVES86KP/view)
[img_ui_hero_story.unity3d](https://drive.google.com/file/d/1-f9BbJjH-zeYpErR8DpGid4oKCNYbfzr/view?usp=sharing)

Thanks you very much for your help and regards!

**Comment by MalitsPlus** [comment]
Specify the Unity version in AssetStudio before importing the assets. In your case it is 2020.3.18f1. 
It's not an unobfuscating issue.

**Comment by thesolitudeofnoblesoul** [comment]
Thank very much!
